<?php $__env->startSection('titulo','Socios | River Mall'); ?>
<?php $__env->startSection('encabezado','Gestión de socios'); ?>
<?php $__env->startSection('contenido'); ?>
<div class="page-heading d-flex flex-wrap justify-content-between gap-3 mb-4"><div><h1 class="h3 mb-1">Socios</h1><p class="mb-0">Administre los propietarios registrados en la cooperativa.</p></div><a class="btn btn-primary align-self-center" href="<?php echo e(route('socios.create')); ?>"><i class="bi bi-plus-lg me-1"></i> Nuevo socio</a></div>
<div class="card"><div class="card-body p-4">
<?php echo $__env->make('componentes.buscador',['placeholder'=>'Buscar por nombre o cédula','opcionesOrden'=>['created_at'=>'Más recientes','nombres'=>'Nombres','apellidos'=>'Apellidos','cedula'=>'Cédula','estado'=>'Estado']], \Illuminate\Support\Arr::except(get_defined_vars(), ['__data', '__path']))->render(); ?>
<div class="table-responsive"><table class="table table-hover align-middle mb-0"><thead><tr><th>Socio</th><th>Cédula</th><th>Contacto</th><th>Dirección</th><th>Estado</th><th class="text-end">Acciones</th></tr></thead><tbody>
<?php $__empty_1 = true; $__currentLoopData = $socios; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $socio): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); $__empty_1 = false; ?><tr><td><strong><?php echo e($socio->nombres); ?> <?php echo e($socio->apellidos); ?></strong><small class="d-block text-muted">Registro #<?php echo e($socio->id); ?></small></td><td><?php echo e($socio->cedula); ?></td><td><?php echo e($socio->telefono); ?><small class="d-block text-muted"><?php echo e($socio->correo ?: 'Sin correo registrado'); ?></small></td><td><?php echo e($socio->direccion); ?></td><td><span class="badge text-bg-<?php echo e($socio->estado==='Activo'?'success':'secondary'); ?>"><?php echo e($socio->estado); ?></span></td><td class="text-end text-nowrap"><a class="btn btn-sm btn-light" href="<?php echo e(route('socios.edit',$socio)); ?>" title="Editar"><i class="bi bi-pencil-square"></i></a> <form class="d-inline" method="POST" action="<?php echo e(route('socios.destroy',$socio)); ?>" data-confirmar-eliminar><?php echo csrf_field(); ?> <?php echo method_field('DELETE'); ?><button class="btn btn-sm btn-outline-danger" title="Eliminar"><i class="bi bi-trash3"></i></button></form></td></tr>
<?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); if ($__empty_1): ?><tr><td colspan="6" class="text-center py-5 text-muted"><i class="bi bi-inbox fs-2 d-block mb-2"></i>No existen socios registrados.</td></tr><?php endif; ?>
</tbody></table></div><div class="d-flex justify-content-end"><?php echo e($socios->links()); ?></div></div></div>
<?php $__env->stopSection(); ?>

<?php echo $__env->make('plantillas.principal', \Illuminate\Support\Arr::except(get_defined_vars(), ['__data', '__path']))->render(); ?><?php /**PATH C:\Xampp\htdocs\COOPERATIVA\resources\views/socios/lista.blade.php ENDPATH**/ ?>