<?php $__env->startSection('titulo','Taxis | River Mall'); ?> <?php $__env->startSection('encabezado','Gestión de taxis'); ?>
<?php $__env->startSection('contenido'); ?>
<div class="page-heading d-flex flex-wrap justify-content-between gap-3 mb-4"><div><h1 class="h3 mb-1">Taxis</h1><p class="mb-0">Unidades vehiculares registradas en la cooperativa.</p></div><a class="btn btn-primary align-self-center" href="<?php echo e(route('taxis.create')); ?>"><i class="bi bi-plus-lg me-1"></i> Nuevo taxi</a></div>
<div class="card"><div class="card-body p-4"><?php echo $__env->make('componentes.buscador',['placeholder'=>'Buscar por placa, marca o modelo','opcionesOrden'=>['created_at'=>'Más recientes','placa'=>'Placa','marca'=>'Marca','modelo'=>'Modelo','año'=>'Año','estado'=>'Estado']], \Illuminate\Support\Arr::except(get_defined_vars(), ['__data', '__path']))->render(); ?>
<div class="table-responsive"><table class="table table-hover align-middle mb-0"><thead><tr><th>Placa</th><th>Vehículo</th><th>Socio</th><th>Conductor</th><th>Color / Año</th><th>Estado</th><th class="text-end">Acciones</th></tr></thead><tbody>
<?php $__empty_1 = true; $__currentLoopData = $taxis; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $taxi): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); $__empty_1 = false; ?><tr><td><span class="badge text-bg-dark"><?php echo e(strtoupper($taxi->placa)); ?></span></td><td><strong><?php echo e($taxi->marca); ?> <?php echo e($taxi->modelo); ?></strong></td><td><?php echo e($taxi->socio?->nombres); ?> <?php echo e($taxi->socio?->apellidos); ?></td><td><?php echo e($taxi->conductor?->nombres); ?> <?php echo e($taxi->conductor?->apellidos); ?></td><td><?php echo e($taxi->color); ?> · <?php echo e($taxi->{'año'}); ?></td><td><span class="badge text-bg-<?php echo e($taxi->estado==='Disponible'?'success':($taxi->estado==='Mantenimiento'?'warning':'primary')); ?>"><?php echo e($taxi->estado); ?></span></td><td class="text-end text-nowrap"><a class="btn btn-sm btn-light" href="<?php echo e(route('taxis.edit',$taxi)); ?>"><i class="bi bi-pencil-square"></i></a> <form class="d-inline" method="POST" action="<?php echo e(route('taxis.destroy',$taxi)); ?>" data-confirmar-eliminar><?php echo csrf_field(); ?> <?php echo method_field('DELETE'); ?><button class="btn btn-sm btn-outline-danger"><i class="bi bi-trash3"></i></button></form></td></tr>
<?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); if ($__empty_1): ?><tr><td colspan="7" class="text-center py-5 text-muted"><i class="bi bi-inbox fs-2 d-block mb-2"></i>No existen taxis registrados.</td></tr><?php endif; ?>
</tbody></table></div><div class="d-flex justify-content-end"><?php echo e($taxis->links()); ?></div></div></div>
<?php $__env->stopSection(); ?>

<?php echo $__env->make('plantillas.principal', \Illuminate\Support\Arr::except(get_defined_vars(), ['__data', '__path']))->render(); ?><?php /**PATH C:\Xampp\htdocs\COOPERATIVA\resources\views/taxis/lista.blade.php ENDPATH**/ ?>