<?php $__env->startSection('titulo','Pagos | River Mall'); ?> <?php $__env->startSection('encabezado','Gestión de pagos'); ?>
<?php $__env->startSection('contenido'); ?>
<div class="page-heading d-flex flex-wrap justify-content-between gap-3 mb-4"><div><h1 class="h3 mb-1">Pagos</h1><p class="mb-0">Control económico de los servicios realizados.</p></div><a class="btn btn-primary align-self-center" href="<?php echo e(route('pagos.create')); ?>"><i class="bi bi-plus-lg me-1"></i> Nuevo pago</a></div>
<div class="card"><div class="card-body p-4"><?php echo $__env->make('componentes.buscador',['placeholder'=>'Buscar por cliente o método de pago','opcionesOrden'=>['fecha_pago'=>'Fecha de pago','created_at'=>'Más recientes','monto'=>'Monto','metodo_pago'=>'Método']], \Illuminate\Support\Arr::except(get_defined_vars(), ['__data', '__path']))->render(); ?>
<div class="table-responsive"><table class="table table-hover align-middle mb-0"><thead><tr><th>Fecha</th><th>Servicio</th><th>Cliente</th><th>Método</th><th>Monto</th><th class="text-end">Acciones</th></tr></thead><tbody>
<?php $__empty_1 = true; $__currentLoopData = $pagos; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $pago): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); $__empty_1 = false; ?><tr><td><?php echo e(optional($pago->fecha_pago)->format('d/m/Y')); ?></td><td><strong>#<?php echo e($pago->servicio_id); ?></strong><small class="d-block text-muted"><?php echo e($pago->servicio?->origen); ?> → <?php echo e($pago->servicio?->destino); ?></small></td><td><?php echo e($pago->servicio?->cliente?->nombres); ?> <?php echo e($pago->servicio?->cliente?->apellidos); ?></td><td><span class="badge text-bg-light"><?php echo e($pago->metodo_pago); ?></span></td><td><strong class="text-success">$<?php echo e(number_format($pago->monto,2)); ?></strong></td><td class="text-end text-nowrap"><a class="btn btn-sm btn-light" href="<?php echo e(route('pagos.edit',$pago)); ?>"><i class="bi bi-pencil-square"></i></a> <form class="d-inline" method="POST" action="<?php echo e(route('pagos.destroy',$pago)); ?>" data-confirmar-eliminar><?php echo csrf_field(); ?> <?php echo method_field('DELETE'); ?><button class="btn btn-sm btn-outline-danger"><i class="bi bi-trash3"></i></button></form></td></tr>
<?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); if ($__empty_1): ?><tr><td colspan="6" class="text-center py-5 text-muted"><i class="bi bi-inbox fs-2 d-block mb-2"></i>No existen pagos registrados.</td></tr><?php endif; ?>
</tbody></table></div><div class="d-flex justify-content-end"><?php echo e($pagos->links()); ?></div></div></div>
<?php $__env->stopSection(); ?>

<?php echo $__env->make('plantillas.principal', \Illuminate\Support\Arr::except(get_defined_vars(), ['__data', '__path']))->render(); ?><?php /**PATH C:\Xampp\htdocs\COOPERATIVA\resources\views/pagos/lista.blade.php ENDPATH**/ ?>