<?php $__env->startSection('titulo','Servicios | River Mall'); ?> <?php $__env->startSection('encabezado','Gestión de servicios'); ?>
<?php $__env->startSection('contenido'); ?>
<div class="page-heading d-flex flex-wrap justify-content-between gap-3 mb-4"><div><h1 class="h3 mb-1">Servicios</h1><p class="mb-0">Carreras y recorridos gestionados por la cooperativa.</p></div><a class="btn btn-primary align-self-center" href="<?php echo e(route('servicios.create')); ?>"><i class="bi bi-plus-lg me-1"></i> Nuevo servicio</a></div>
<div class="card"><div class="card-body p-4"><?php echo $__env->make('componentes.buscador',['placeholder'=>'Buscar por origen, destino o estado','opcionesOrden'=>['fecha'=>'Fecha','created_at'=>'Más recientes','valor'=>'Valor','estado'=>'Estado']], \Illuminate\Support\Arr::except(get_defined_vars(), ['__data', '__path']))->render(); ?>
<div class="table-responsive"><table class="table table-hover align-middle mb-0"><thead><tr><th>Fecha</th><th>Cliente</th><th>Conductor / Taxi</th><th>Ruta</th><th>Valor</th><th>Estado</th><th class="text-end">Acciones</th></tr></thead><tbody>
<?php $__empty_1 = true; $__currentLoopData = $servicios; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $servicio): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); $__empty_1 = false; ?><tr><td><?php echo e(optional($servicio->fecha)->format('d/m/Y')); ?><small class="d-block text-muted"><?php echo e(substr($servicio->hora,0,5)); ?></small></td><td><strong><?php echo e($servicio->cliente?->nombres); ?> <?php echo e($servicio->cliente?->apellidos); ?></strong></td><td><?php echo e($servicio->conductor?->nombres); ?> <?php echo e($servicio->conductor?->apellidos); ?><small class="d-block text-muted">Unidad <?php echo e($servicio->taxi?->placa); ?></small></td><td><?php echo e($servicio->origen); ?> <i class="bi bi-arrow-right mx-1 text-primary"></i> <?php echo e($servicio->destino); ?></td><td><strong>$<?php echo e(number_format($servicio->valor,2)); ?></strong></td><td><span class="badge text-bg-<?php echo e($servicio->estado==='Finalizado'?'success':($servicio->estado==='Cancelado'?'danger':($servicio->estado==='En curso'?'primary':'warning'))); ?>"><?php echo e($servicio->estado); ?></span></td><td class="text-end text-nowrap"><a class="btn btn-sm btn-light" href="<?php echo e(route('servicios.edit',$servicio)); ?>"><i class="bi bi-pencil-square"></i></a> <form class="d-inline" method="POST" action="<?php echo e(route('servicios.destroy',$servicio)); ?>" data-confirmar-eliminar><?php echo csrf_field(); ?> <?php echo method_field('DELETE'); ?><button class="btn btn-sm btn-outline-danger"><i class="bi bi-trash3"></i></button></form></td></tr>
<?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); if ($__empty_1): ?><tr><td colspan="7" class="text-center py-5 text-muted"><i class="bi bi-inbox fs-2 d-block mb-2"></i>No existen servicios registrados.</td></tr><?php endif; ?>
</tbody></table></div><div class="d-flex justify-content-end"><?php echo e($servicios->links()); ?></div></div></div>
<?php $__env->stopSection(); ?>

<?php echo $__env->make('plantillas.principal', \Illuminate\Support\Arr::except(get_defined_vars(), ['__data', '__path']))->render(); ?><?php /**PATH C:\Xampp\htdocs\COOPERATIVA\resources\views/servicios/lista.blade.php ENDPATH**/ ?>