<?php $__env->startSection('titulo','Conductores | River Mall'); ?> <?php $__env->startSection('encabezado','Gestión de conductores'); ?>
<?php $__env->startSection('contenido'); ?>
<div class="page-heading d-flex flex-wrap justify-content-between gap-3 mb-4"><div><h1 class="h3 mb-1">Conductores</h1><p class="mb-0">Personal autorizado para operar las unidades.</p></div><a class="btn btn-primary align-self-center" href="<?php echo e(route('conductores.create')); ?>"><i class="bi bi-plus-lg me-1"></i> Nuevo conductor</a></div>
<div class="card"><div class="card-body p-4"><?php echo $__env->make('componentes.buscador',['placeholder'=>'Buscar por nombre, cédula o licencia','opcionesOrden'=>['created_at'=>'Más recientes','nombres'=>'Nombres','apellidos'=>'Apellidos','cedula'=>'Cédula','licencia'=>'Licencia','estado'=>'Estado']], \Illuminate\Support\Arr::except(get_defined_vars(), ['__data', '__path']))->render(); ?>
<div class="table-responsive"><table class="table table-hover align-middle mb-0"><thead><tr><th>Conductor</th><th>Socio responsable</th><th>Cédula</th><th>Licencia</th><th>Teléfono</th><th>Estado</th><th class="text-end">Acciones</th></tr></thead><tbody>
<?php $__empty_1 = true; $__currentLoopData = $conductores; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $conductor): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); $__empty_1 = false; ?><tr><td><strong><?php echo e($conductor->nombres); ?> <?php echo e($conductor->apellidos); ?></strong></td><td><?php echo e($conductor->socio?->nombres); ?> <?php echo e($conductor->socio?->apellidos); ?></td><td><?php echo e($conductor->cedula); ?></td><td><?php echo e($conductor->licencia); ?></td><td><?php echo e($conductor->telefono); ?></td><td><span class="badge text-bg-<?php echo e($conductor->estado==='Activo'?'success':'secondary'); ?>"><?php echo e($conductor->estado); ?></span></td><td class="text-end text-nowrap"><a class="btn btn-sm btn-light" href="<?php echo e(route('conductores.edit',$conductor)); ?>"><i class="bi bi-pencil-square"></i></a> <form class="d-inline" method="POST" action="<?php echo e(route('conductores.destroy',$conductor)); ?>" data-confirmar-eliminar><?php echo csrf_field(); ?> <?php echo method_field('DELETE'); ?><button class="btn btn-sm btn-outline-danger"><i class="bi bi-trash3"></i></button></form></td></tr>
<?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); if ($__empty_1): ?><tr><td colspan="7" class="text-center py-5 text-muted"><i class="bi bi-inbox fs-2 d-block mb-2"></i>No existen conductores registrados.</td></tr><?php endif; ?>
</tbody></table></div><div class="d-flex justify-content-end"><?php echo e($conductores->links()); ?></div></div></div>
<?php $__env->stopSection(); ?>

<?php echo $__env->make('plantillas.principal', \Illuminate\Support\Arr::except(get_defined_vars(), ['__data', '__path']))->render(); ?><?php /**PATH C:\Xampp\htdocs\COOPERATIVA\resources\views/conductores/lista.blade.php ENDPATH**/ ?>