<?php $__env->startSection('titulo','Clientes | River Mall'); ?> <?php $__env->startSection('encabezado','Gestión de clientes'); ?>
<?php $__env->startSection('contenido'); ?>
<div class="page-heading d-flex flex-wrap justify-content-between gap-3 mb-4"><div><h1 class="h3 mb-1">Clientes</h1><p class="mb-0">Personas que solicitan los servicios de transporte.</p></div><a class="btn btn-primary align-self-center" href="<?php echo e(route('clientes.create')); ?>"><i class="bi bi-plus-lg me-1"></i> Nuevo cliente</a></div>
<div class="card"><div class="card-body p-4"><?php echo $__env->make('componentes.buscador',['placeholder'=>'Buscar por nombre o cédula','opcionesOrden'=>['created_at'=>'Más recientes','nombres'=>'Nombres','apellidos'=>'Apellidos','cedula'=>'Cédula']], \Illuminate\Support\Arr::except(get_defined_vars(), ['__data', '__path']))->render(); ?>
<div class="table-responsive"><table class="table table-hover align-middle mb-0"><thead><tr><th>Cliente</th><th>Cédula</th><th>Teléfono</th><th>Dirección</th><th>Correo</th><th class="text-end">Acciones</th></tr></thead><tbody>
<?php $__empty_1 = true; $__currentLoopData = $clientes; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $cliente): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); $__empty_1 = false; ?><tr><td><strong><?php echo e($cliente->nombres); ?> <?php echo e($cliente->apellidos); ?></strong></td><td><?php echo e($cliente->cedula); ?></td><td><?php echo e($cliente->telefono); ?></td><td><?php echo e($cliente->direccion); ?></td><td><?php echo e($cliente->correo ?: '—'); ?></td><td class="text-end text-nowrap"><a class="btn btn-sm btn-light" href="<?php echo e(route('clientes.edit',$cliente)); ?>" title="Editar"><i class="bi bi-pencil-square"></i></a> <form class="d-inline" method="POST" action="<?php echo e(route('clientes.destroy',$cliente)); ?>" data-confirmar-eliminar><?php echo csrf_field(); ?> <?php echo method_field('DELETE'); ?><button class="btn btn-sm btn-outline-danger" title="Eliminar"><i class="bi bi-trash3"></i></button></form></td></tr>
<?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); if ($__empty_1): ?><tr><td colspan="6" class="text-center py-5 text-muted"><i class="bi bi-inbox fs-2 d-block mb-2"></i>No existen clientes registrados.</td></tr><?php endif; ?>
</tbody></table></div><div class="d-flex justify-content-end"><?php echo e($clientes->links()); ?></div></div></div>
<?php $__env->stopSection(); ?>

<?php echo $__env->make('plantillas.principal', \Illuminate\Support\Arr::except(get_defined_vars(), ['__data', '__path']))->render(); ?><?php /**PATH C:\Xampp\htdocs\COOPERATIVA\resources\views/clientes/lista.blade.php ENDPATH**/ ?>