@extends('plantillas.principal')
@section('titulo','Taxis | River Mall') @section('encabezado','Gestión de taxis')
@section('contenido')
<div class="page-heading d-flex flex-wrap justify-content-between gap-3 mb-4"><div><h1 class="h3 mb-1">Taxis</h1><p class="mb-0">Unidades vehiculares registradas en la cooperativa.</p></div><a class="btn btn-primary align-self-center" href="{{ route('taxis.create') }}"><i class="bi bi-plus-lg me-1"></i> Nuevo taxi</a></div>
<div class="card"><div class="card-body p-4">@include('componentes.buscador',['placeholder'=>'Buscar por placa, marca o modelo','opcionesOrden'=>['created_at'=>'Más recientes','placa'=>'Placa','marca'=>'Marca','modelo'=>'Modelo','año'=>'Año','estado'=>'Estado']])
<div class="table-responsive"><table class="table table-hover align-middle mb-0"><thead><tr><th>Placa</th><th>Vehículo</th><th>Socio</th><th>Conductor</th><th>Color / Año</th><th>Estado</th><th class="text-end">Acciones</th></tr></thead><tbody>
@forelse($taxis as $taxi)<tr><td><span class="badge text-bg-dark">{{ strtoupper($taxi->placa) }}</span></td><td><strong>{{ $taxi->marca }} {{ $taxi->modelo }}</strong></td><td>{{ $taxi->socio?->nombres }} {{ $taxi->socio?->apellidos }}</td><td>{{ $taxi->conductor?->nombres }} {{ $taxi->conductor?->apellidos }}</td><td>{{ $taxi->color }} · {{ $taxi->{'año'} }}</td><td><span class="badge text-bg-{{ $taxi->estado==='Disponible'?'success':($taxi->estado==='Mantenimiento'?'warning':'primary') }}">{{ $taxi->estado }}</span></td><td class="text-end text-nowrap"><a class="btn btn-sm btn-light" href="{{ route('taxis.edit',$taxi) }}"><i class="bi bi-pencil-square"></i></a> <form class="d-inline" method="POST" action="{{ route('taxis.destroy',$taxi) }}" data-confirmar-eliminar>@csrf @method('DELETE')<button class="btn btn-sm btn-outline-danger"><i class="bi bi-trash3"></i></button></form></td></tr>
@empty<tr><td colspan="7" class="text-center py-5 text-muted"><i class="bi bi-inbox fs-2 d-block mb-2"></i>No existen taxis registrados.</td></tr>@endforelse
</tbody></table></div><div class="d-flex justify-content-end">{{ $taxis->links() }}</div></div></div>
@endsection
