@extends('plantillas.principal')
@section('titulo','Servicios | River Mall') @section('encabezado','Gestión de servicios')
@section('contenido')
<div class="page-heading d-flex flex-wrap justify-content-between gap-3 mb-4"><div><h1 class="h3 mb-1">Servicios</h1><p class="mb-0">Carreras y recorridos gestionados por la cooperativa.</p></div><a class="btn btn-primary align-self-center" href="{{ route('servicios.create') }}"><i class="bi bi-plus-lg me-1"></i> Nuevo servicio</a></div>
<div class="card"><div class="card-body p-4">@include('componentes.buscador',['placeholder'=>'Buscar por origen, destino o estado','opcionesOrden'=>['fecha'=>'Fecha','created_at'=>'Más recientes','valor'=>'Valor','estado'=>'Estado']])
<div class="table-responsive"><table class="table table-hover align-middle mb-0"><thead><tr><th>Fecha</th><th>Cliente</th><th>Conductor / Taxi</th><th>Ruta</th><th>Valor</th><th>Estado</th><th class="text-end">Acciones</th></tr></thead><tbody>
@forelse($servicios as $servicio)<tr><td>{{ optional($servicio->fecha)->format('d/m/Y') }}<small class="d-block text-muted">{{ substr($servicio->hora,0,5) }}</small></td><td><strong>{{ $servicio->cliente?->nombres }} {{ $servicio->cliente?->apellidos }}</strong></td><td>{{ $servicio->conductor?->nombres }} {{ $servicio->conductor?->apellidos }}<small class="d-block text-muted">Unidad {{ $servicio->taxi?->placa }}</small></td><td>{{ $servicio->origen }} <i class="bi bi-arrow-right mx-1 text-primary"></i> {{ $servicio->destino }}</td><td><strong>${{ number_format($servicio->valor,2) }}</strong></td><td><span class="badge text-bg-{{ $servicio->estado==='Finalizado'?'success':($servicio->estado==='Cancelado'?'danger':($servicio->estado==='En curso'?'primary':'warning')) }}">{{ $servicio->estado }}</span></td><td class="text-end text-nowrap"><a class="btn btn-sm btn-light" href="{{ route('servicios.edit',$servicio) }}"><i class="bi bi-pencil-square"></i></a> <form class="d-inline" method="POST" action="{{ route('servicios.destroy',$servicio) }}" data-confirmar-eliminar>@csrf @method('DELETE')<button class="btn btn-sm btn-outline-danger"><i class="bi bi-trash3"></i></button></form></td></tr>
@empty<tr><td colspan="7" class="text-center py-5 text-muted"><i class="bi bi-inbox fs-2 d-block mb-2"></i>No existen servicios registrados.</td></tr>@endforelse
</tbody></table></div><div class="d-flex justify-content-end">{{ $servicios->links() }}</div></div></div>
@endsection
